name: 'Generic: Checkstyle'

on:
  workflow_call:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: dbelyaev/action-checkstyle@v0.8.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_version: 10.12.2
          checkstyle_config: ./config/mv_checks.xml
